
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `admin_data.dart` with the code generated by Freezed
part 'admin_data.freezed.dart';
// optional: Since our AdminData class is serializable, we must add this line.
// But if AdminData was not serializable, we could skip it.
part 'admin_data.g.dart';

/* To create the data model or to apply changes in the data model or there's modification in the method for @JsonKey(),
execute this command in terminal: dart run build_runner build --delete-conflicting-outputs*/

@freezed
class AdminData with _$AdminData {
  factory AdminData({
    @JsonKey(name: "admin_id") String? adminID,
    @JsonKey(name: "username") String? username,
    @JsonKey(name: "full_name") String? fullName,
    @JsonKey(name: "comp_email") String? compEmail,
    @JsonKey(name: "admin_role") String? adminRole,
  }) = _AdminData;

  factory AdminData.fromJson(Map<String, dynamic> json) =>
      _$AdminDataFromJson(json);
}