import 'dart:convert';
import 'dart:typed_data';

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `image_data.dart` with the code generated by Freezed
part 'image_data.freezed.dart';
// optional: Since our Image class is serializable, we must add this line.
// But if Image was not serializable, we could skip it.
part 'image_data.g.dart';

// Uint8List? _fileFromJson(String? base64String) {
//   if (base64String == null) return null;
//   return Uri.parse(base64String).data?.contentAsBytes();
// } // not working

// String? _fileToJson(Uint8List? fileBytes) {
//   if (fileBytes == null) return null;
//   return 'data:application/octet-stream;base64,${base64Encode(fileBytes)}';
// } // not working

// Convert Base64 to Uint8List
Uint8List? _fromBase64(String? base64String) {
  if (base64String == null) return null;
  return base64Decode(base64String);
}

// Convert Uint8List to Base64 String
String? _toBase64(Uint8List? bytes) {
  if (bytes == null) return null;
  return base64Encode(bytes);
}

/* To create the data model or to apply changes in the data model or there's modification in the method for @JsonKey(),
execute this command in terminal: dart run build_runner build --delete-conflicting-outputs*/

// Model for a Single ImageData
@freezed
class ImageData with _$ImageData {
  // not sure if it useful yet
  factory ImageData({
    @JsonKey(name: "img_id") String? imgId,
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? img,
    // required double imgSize, // Ensure size is required // I am not using this for the meantime
  }) = _ImageData;

  factory ImageData.fromJson(Map<String, dynamic> json) =>
      _$ImageDataFromJson(json);
}
@freezed
class ImageProdVarData with _$ImageProdVarData {
  // not sure if it useful yet
  factory ImageProdVarData({
    @JsonKey(name: "img_id") String? imgId,
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? img,
    // required double imgSize, // Ensure size is required // I am not using this for the meantime
  }) = _ImageProdVarData;

  factory ImageProdVarData.fromJson(Map<String, dynamic> json) =>
      _$ImageProdVarDataFromJson(json);
}

@freezed
class ImageDatawSub with _$ImageDatawSub {
  // not sure if it useful yet
  factory ImageDatawSub({
    @JsonKey(name: "prod_id") String? prodId,
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? img,
    @JsonKey(name: "tag") String? tag,
    // required double imgSize, // Ensure size is required // I am not using this for the meantime
  }) = _ImageDatawSub;

  factory ImageDatawSub.fromJson(Map<String, dynamic> json) =>
      _$ImageDatawSubFromJson(json);
}
