import 'dart:convert';
import 'dart:typed_data';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:glamgear/internal/data_model/freezed/image_data.dart';
import 'package:glamgear/internal/data_model/freezed/prdct_admin_data.dart';

// required: associates our `prdct_client_data.dart` with the code generated by Freezed
part 'prdct_client_data.freezed.dart';
// optional: Since our ProductClientDashboardData class is serializable, we must add this line.
// But if ProductClientDashboardData was not serializable, we could skip it.
part 'prdct_client_data.g.dart';

/* To create the data model or to apply changes in the data model or there's modification in the method for @JsonKey(),
execute this command in terminal: dart run build_runner build --delete-conflicting-outputs*/

List<ProductDashboardData> _productClientDbFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map(
          (json) => ProductDashboardData.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _productClientDbToJson(
    List<ProductDashboardData>? productDataList) {
  return productDataList?.map((data) => data.toJson()).toList() ?? [];
}

List<ProductPreviewData> _prodClientPVFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ProductPreviewData.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _prodClientPVToJson(List<ProductPreviewData>? productDataList) {
  return productDataList?.map((data) => data.toJson()).toList() ?? [];
}

List<ProductMainPropertiesPreviewData> _prodMainPropFromJson(
    List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ProductMainPropertiesPreviewData.fromJson(
          json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _prodMainPropToJson(
    List<ProductMainPropertiesPreviewData>? prodMainPropList) {
  return prodMainPropList?.map((data) => data.toJson()).toList() ?? [];
}

List<ProductPromoTag> _prodPromoTagFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ProductPromoTag.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _prodPromoTagToJson(List<ProductPromoTag>? prodPromoTagList) {
  return prodPromoTagList?.map((data) => data.toJson()).toList() ?? [];
}

List<ImageData> _imageDataFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ImageData.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _imageDataToJson(List<ImageData>? imageDataList) {
  return imageDataList?.map((data) => data.toJson()).toList() ?? [];
}

List<ImageDatawSub> _imageDatawSubFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ImageDatawSub.fromJson(json as Map<String, dynamic>))
      .toList();
} // needed to add another method

List<dynamic> _imageDatawSubToJson(List<ImageDatawSub>? imageDataList) {
  return imageDataList?.map((data) => data.toJson()).toList() ?? [];
}

List<ImageProdVarData> _imageProdVarDataFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ImageProdVarData.fromJson(json as Map<String, dynamic>))
      .toList();
} // needed to add another method

List<dynamic> _imageProdVarDataToJson(List<ImageProdVarData>? imageDataList) {
  return imageDataList?.map((data) => data.toJson()).toList() ?? [];
}

List<ProductClientKeyValue> _prodKeyValFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) =>
          ProductClientKeyValue.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _prodKeyValToJson(List<ProductClientKeyValue>? prodKeyValList) {
  return prodKeyValList?.map((data) => data.toJson()).toList() ?? [];
}

List<ProductVarClientKeyValue> _prodVarKeyValFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) =>
          ProductVarClientKeyValue.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _prodVarKeyValToJson(
    List<ProductVarClientKeyValue>? prodKeyValList) {
  return prodKeyValList?.map((data) => data.toJson()).toList() ?? [];
}

List<ProductVariantPreviewData> _prodVarPreviewFromJson(
    List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) =>
          ProductVariantPreviewData.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _prodVarPreviewToJson(
    List<ProductVariantPreviewData>? prodKeyValList) {
  return prodKeyValList?.map((data) => data.toJson()).toList() ?? [];
}

// String _prodDescFromJson(List<dynamic>? rawJson) {
//   return jsonEncode(rawJson ?? []);
// }

List<dynamic> _prodDescToJson(String? rawJson) {
  return jsonDecode(rawJson ?? '[]');
}

// Convert Base64 to Uint8List
Uint8List? _fromBase64(String? base64String) {
  if (base64String == null) return null;
  return base64Decode(base64String);
}

// Convert Uint8List to Base64 String
String? _toBase64(Uint8List? bytes) {
  if (bytes == null) return null;
  return base64Encode(bytes);
}

@freezed
class UserVerificationStatus with _$UserVerificationStatus {
  factory UserVerificationStatus({
    @JsonKey(name: "role_type") String? roleType,
    @JsonKey(name: "pending_ver") bool? isPendingVerification,
    @JsonKey(name: "is_verified") bool? isVerified,
    @JsonKey(name: "remarks") String? remarks,
    @JsonKey(name: "modif_lvl") String? modificationLevel,
  }) = _UserVerificationStatus;

  factory UserVerificationStatus.fromJson(Map<String, dynamic> json) =>
      _$UserVerificationStatusFromJson(json);
}

@freezed
class CounterState with _$CounterState {
  // for reference only
  const factory CounterState({required int count}) = _CounterState;

  factory CounterState.initial() => const CounterState(count: 0);
}

@freezed
class ProductClientDashboardData with _$ProductClientDashboardData {
  factory ProductClientDashboardData({
    @JsonKey(
        name: "json_data",
        fromJson: _productClientDbFromJson,
        toJson: _productClientDbToJson)
    List<ProductDashboardData>? productData,
  }) = _ProductClientDashboardData;

  factory ProductClientDashboardData.fromJson(Map<String, dynamic> json) =>
      _$ProductClientDashboardDataFromJson(json);
}

@freezed
class ProductDashboardData with _$ProductDashboardData {
  factory ProductDashboardData({
    @JsonKey(name: "prod_id") String? prodId,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "orig_price") double? origPrice,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "dis_perc") String? disPerc,
    @JsonKey(
        name: "nested_p_tag_key",
        fromJson: _prodPromoTagFromJson,
        toJson: _prodPromoTagToJson)
    List<ProductPromoTag>? prodPromoTag,
    @JsonKey(
        name: "nested_p_img_key",
        fromJson: _imageDataFromJson,
        toJson: _imageDataToJson)
    List<ImageData>? prodImg, // List of images with id
  }) = _ProductDashboardData;

  factory ProductDashboardData.fromJson(Map<String, dynamic> json) =>
      _$ProductDashboardDataFromJson(json);
}

@freezed
class ProductClientPreviewData with _$ProductClientPreviewData {
  factory ProductClientPreviewData({
    @JsonKey(fromJson: _prodClientPVFromJson, toJson: _prodClientPVToJson)
    List<ProductPreviewData>? productData,
  }) = _ProductClientPreviewData;

  factory ProductClientPreviewData.fromJson(Map<String, dynamic> json) =>
      _$ProductClientPreviewDataFromJson(json);
}

@freezed
class ProductClientPreviewImgData with _$ProductClientPreviewImgData {
  factory ProductClientPreviewImgData({
    @JsonKey(
        name: "nested_pv_img_key",
        fromJson: _imageDatawSubFromJson,
        toJson: _imageDatawSubToJson)
    List<ImageDatawSub>? prodImg, // List of images with id
  }) = _ProductClientPreviewImgData;

  factory ProductClientPreviewImgData.fromJson(Map<String, dynamic> json) =>
      _$ProductClientPreviewImgDataFromJson(json);
}

@freezed
class ProductClientPreviewFullDescData with _$ProductClientPreviewFullDescData {
  factory ProductClientPreviewFullDescData({
    @JsonKey(
      name: "desc_data",
      // fromJson: _prodDescFromJson,
      toJson: _prodDescToJson,
    )
    String? prodDescription,
  }) = _ProductClientPreviewFullDescData;

  factory ProductClientPreviewFullDescData.fromJson(
          Map<String, dynamic> json) =>
      _$ProductClientPreviewFullDescDataFromJson(json);
}

@freezed
class ProductPreviewData with _$ProductPreviewData {
  factory ProductPreviewData({
    @JsonKey(name: "nested_prod_var")
    List<ProductVariantGetterData>? prodVarData,
    @JsonKey(
        name: "nested_prod_key",
        fromJson: _prodMainPropFromJson,
        toJson: _prodMainPropToJson)
    List<ProductMainPropertiesPreviewData>? prodMainPropPD,
    @JsonKey(
        name: "nested_p_tag_key",
        fromJson: _prodPromoTagFromJson,
        toJson: _prodPromoTagToJson)
    List<ProductPromoTag>? prodPromoTag,
    @JsonKey(
        name: "nested_specs_key",
        fromJson: _prodKeyValFromJson,
        toJson: _prodKeyValToJson)
    List<ProductClientKeyValue>? prodKeyVal,
  }) = _ProductPreviewData;

  factory ProductPreviewData.fromJson(Map<String, dynamic> json) =>
      _$ProductPreviewDataFromJson(json);
}

@freezed
class BadgeData with _$BadgeData {
  factory BadgeData({
    List<BadgeCounts>?
        badgeData, // required to defined as List<ThisDataModelClass>
  }) = _BadgeData;

  factory BadgeData.fromJson(Map<String, dynamic> json) =>
      _$BadgeDataFromJson(json);
}

@freezed
class BadgeCounts with _$BadgeCounts {
  factory BadgeCounts({
    @JsonKey(name: "cart_badge_cnt") String? cartBdgeCnt,
    @JsonKey(name: "mssg_badge_cnt") String? mssgBdgeCnt,
  }) = _BadgeCounts;

  factory BadgeCounts.fromJson(Map<String, dynamic> json) =>
      _$BadgeCountsFromJson(json);
}

@freezed
class ProductVariantGetterData with _$ProductVariantGetterData {
  factory ProductVariantGetterData({
    @JsonKey(name: "prod_var_id") String? prodVarId,
    @JsonKey(name: "variant_cnt") int? prodVarCount,
  }) = _ProductVariantGetterData;

  factory ProductVariantGetterData.fromJson(Map<String, dynamic> json) =>
      _$ProductVariantGetterDataFromJson(json);
}

@freezed
class ProductMainPropertiesPreviewData with _$ProductMainPropertiesPreviewData {
  factory ProductMainPropertiesPreviewData({
    @JsonKey(name: "prod_id") String? prodId,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "orig_price") double? origPrice,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "dis_perc") String? disPerc,
    @JsonKey(name: "stock") int? stock,
    @JsonKey(name: "availability") bool? availability,
  }) = _ProductMainPropertiesPreviewData;

  factory ProductMainPropertiesPreviewData.fromJson(
          Map<String, dynamic> json) =>
      _$ProductMainPropertiesPreviewDataFromJson(json);
}

@freezed
class ProductVariantSpecs with _$ProductVariantSpecs {
  factory ProductVariantSpecs({
    List<ProductVarPreviewClientKeyValue>? prodVarSpecOptData,
  }) = _ProductVariantSpecs;

  factory ProductVariantSpecs.fromJson(Map<String, dynamic> json) =>
      _$ProductVariantSpecsFromJson(json);
}

@freezed
class ProductVariantPreview with _$ProductVariantPreview {
  factory ProductVariantPreview({
    @JsonKey(fromJson: _prodVarPreviewFromJson, toJson: _prodVarPreviewToJson)
    List<ProductVariantPreviewData>? prodVarPreviewData,
  }) = _ProductVariantPreview;

  factory ProductVariantPreview.fromJson(Map<String, dynamic> json) =>
      _$ProductVariantPreviewFromJson(json);
}

@freezed
class ProductVariantPreviewImgData with _$ProductVariantPreviewImgData {
  factory ProductVariantPreviewImgData({
    @JsonKey(
        name: "nested_pv_img_key",
        fromJson: _imageProdVarDataFromJson,
        toJson: _imageProdVarDataToJson)
    List<ImageProdVarData>? prodImg, // List of images with id
  }) = _ProductVariantPreviewImgData;

  factory ProductVariantPreviewImgData.fromJson(Map<String, dynamic> json) =>
      _$ProductVariantPreviewImgDataFromJson(json);
}

@freezed
class ProductVariantPreviewData with _$ProductVariantPreviewData {
  factory ProductVariantPreviewData({
    @JsonKey(name: "prod_var_id") String? prodVarId,
    @JsonKey(name: "orig_price") double? origPrice,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "dis_perc") String? disPerc,
    @JsonKey(name: "stock") int? stock,
    @JsonKey(name: "value") String? value,
  }) = _ProductVariantPreviewData;

  factory ProductVariantPreviewData.fromJson(Map<String, dynamic> json) =>
      _$ProductVariantPreviewDataFromJson(json);
}

@freezed
class ProductClientKeyValue with _$ProductClientKeyValue {
  factory ProductClientKeyValue({
    @JsonKey(name: "p_key_name_id") String? prodKeyNameID,
    @JsonKey(name: "key_name") String? prodKeyName,
    @JsonKey(name: "value") String? value,
  }) = _ProductClientKeyValue;

  factory ProductClientKeyValue.fromJson(Map<String, dynamic> json) =>
      _$ProductClientKeyValueFromJson(json);
}

@freezed
class ProductVarClientKeyValue with _$ProductVarClientKeyValue {
  factory ProductVarClientKeyValue({
    @JsonKey(name: "prod_var_id") String? prodVarID,
    @JsonKey(name: "key_name") String? prodVKeyName,
    @JsonKey(name: "value") String? value,
  }) = _ProductVarClientKeyValue;

  factory ProductVarClientKeyValue.fromJson(Map<String, dynamic> json) =>
      _$ProductVarClientKeyValueFromJson(json);
}

@freezed
class ProductVarPreviewClientKeyValue with _$ProductVarPreviewClientKeyValue {
  factory ProductVarPreviewClientKeyValue({
    @JsonKey(name: "prod_var_id") String? prodVarID,
    @JsonKey(name: "key_name") String? prodVKeyName,
    @JsonKey(name: "value") String? value,
    @JsonKey(name: "availability") bool? availability,
  }) = _ProductVarPreviewClientKeyValue;

  factory ProductVarPreviewClientKeyValue.fromJson(Map<String, dynamic> json) =>
      _$ProductVarPreviewClientKeyValueFromJson(json);
}

@freezed
class CartListData with _$CartListData {
  factory CartListData({
    List<CartPropertiesData>? cartPropsData,
  }) = _CartListData;

  factory CartListData.fromJson(Map<String, dynamic> json) =>
      _$CartListDataFromJson(json);
}

@freezed
class CartPropertiesData with _$CartPropertiesData {
  factory CartPropertiesData({
    @JsonKey(name: "cart_id") String? cartID,
    @JsonKey(name: "nested_img", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "nested_prod")
    List<CartProdPropertiesData>? cartProdPropData,
    @JsonKey(name: "is_selected") bool? isSelected,
    @JsonKey(name: "quantity") int? quantity,
    @JsonKey(name: "nested_availability") bool? availability,
    @JsonKey(name: "nested_available_qty") int? availableQty,
    @JsonKey(
        name: "nested_pv_specs",
        fromJson: _prodVarKeyValFromJson,
        toJson: _prodVarKeyValToJson)
    List<ProductVarClientKeyValue>? prodVarSpecOptData,
  }) = _CartPropertiesData;

  factory CartPropertiesData.fromJson(Map<String, dynamic> json) =>
      _$CartPropertiesDataFromJson(json);
}

@freezed
class CartProdPropertiesData with _$CartProdPropertiesData {
  factory CartProdPropertiesData({
    @JsonKey(name: "prod_id") String? prodID,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "disc_price") double? discPrice,
  }) = _CartProdPropertiesData;

  factory CartProdPropertiesData.fromJson(Map<String, dynamic> json) =>
      _$CartProdPropertiesDataFromJson(json);
}

@freezed
class CartBottomPropData with _$CartBottomPropData {
  factory CartBottomPropData({
    @JsonKey(name: "is_all_seleted") bool? isAllSelected,
    @JsonKey(name: "subt_price") double? subTotal,
    @JsonKey(name: "t_disc") double? tdiscPrice,
    @JsonKey(name: "t_qty") int? tQuantity,
  }) = _CartBottomPropData;

  factory CartBottomPropData.fromJson(Map<String, dynamic> json) =>
      _$CartBottomPropDataFromJson(json);
}

@freezed
class CheckoutProduct with _$CheckoutProduct {
  factory CheckoutProduct({
    List<CheckoutProductData>? checkoutProductData,
  }) = _CheckoutProduct;

  factory CheckoutProduct.fromJson(Map<String, dynamic> json) =>
      _$CheckoutProductFromJson(json);
}

@freezed
class CheckoutProductData with _$CheckoutProductData {
  factory CheckoutProductData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "value") String? variant,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "quantity") int? quantity,
    @JsonKey(name: "stock") int? stock,
    @JsonKey(name: "tag_values") String? tagValue,
  }) = _CheckoutProductData;

  factory CheckoutProductData.fromJson(Map<String, dynamic> json) =>
      _$CheckoutProductDataFromJson(json);
}

@freezed
class CheckoutProductPricesData with _$CheckoutProductPricesData {
  factory CheckoutProductPricesData({
    @JsonKey(name: "merch_subt") double? merchSubTotal,
    @JsonKey(name: "voucher") double? voucher,
    @JsonKey(name: "ship_f_subt") double? shippingFeeSubTotal,
    @JsonKey(name: "ship_f_disc_subt") double? shippingFeeDiscSubTotal,
    @JsonKey(name: "total") double? total,
    @JsonKey(name: "total_disc") double? totalDisc,
  }) = _CheckoutProductPricesData;

  factory CheckoutProductPricesData.fromJson(Map<String, dynamic> json) =>
      _$CheckoutProductPricesDataFromJson(json);
}

@freezed
class UserShippingAddress with _$UserShippingAddress {
  factory UserShippingAddress({
    List<UserShippingAddressData>? userShippingData,
  }) = _UserShippingAddress;

  factory UserShippingAddress.fromJson(Map<String, dynamic> json) =>
      _$UserShippingAddressFromJson(json);
}

@freezed
class UserShippingAddressDataSingle with _$UserShippingAddressDataSingle {
  factory UserShippingAddressDataSingle({
    @JsonKey(name: "shipping_add_id") String? shippingAddressID,
    @JsonKey(name: "recipients_name") String? recipientName,
    @JsonKey(name: "mobile_no") String? mobileNo,
    @JsonKey(name: "region") String? region,
    @JsonKey(name: "city") String? city,
    @JsonKey(name: "district") String? district,
    @JsonKey(name: "st_bldg") String? stBldg,
    @JsonKey(name: "unit_floor") String? unitFloor,
    @JsonKey(name: "address_category") String? addressCategory,
    @JsonKey(name: "is_default") bool? isDefault,
    @JsonKey(name: "is_selected") bool? isSelected,
  }) = _UserShippingAddressDataSingle;

  factory UserShippingAddressDataSingle.fromJson(Map<String, dynamic> json) =>
      _$UserShippingAddressDataSingleFromJson(json);
}

@freezed
class UserShippingAddressData with _$UserShippingAddressData {
  factory UserShippingAddressData({
    @JsonKey(name: "shipping_add_id") String? shippingAddressID,
    @JsonKey(name: "recipients_name") String? recipientName,
    @JsonKey(name: "mobile_no") String? mobileNo,
    @JsonKey(name: "region") String? region,
    @JsonKey(name: "city") String? city,
    @JsonKey(name: "district") String? district,
    @JsonKey(name: "st_bldg") String? stBldg,
    @JsonKey(name: "unit_floor") String? unitFloor,
    @JsonKey(name: "address_category") String? addressCategory,
    @JsonKey(name: "is_default") bool? isDefault,
    @JsonKey(name: "is_selected") bool? isSelected,
  }) = _UserShippingAddressData;

  factory UserShippingAddressData.fromJson(Map<String, dynamic> json) =>
      _$UserShippingAddressDataFromJson(json);
}

/// Start of My Orders To Pay /// [TO ADD MORE GRANULAR CONTROL TO THE DATA MODEL]

@freezed
class DisplayNameMyOrdersBadgeCounts with _$DisplayNameMyOrdersBadgeCounts {
  factory DisplayNameMyOrdersBadgeCounts({
    @JsonKey(name: "disp_name") String? displayName,
    @JsonKey(name: "tp_bc") String? toPayBC,
    @JsonKey(name: "ts_bc") String? toShipBC,
    @JsonKey(name: "tr_bc") String? toReceiveBC,
  }) = _DisplayNameMyOrdersBadgeCounts;

  factory DisplayNameMyOrdersBadgeCounts.fromJson(Map<String, dynamic> json) =>
      _$DisplayNameMyOrdersBadgeCountsFromJson(json);
}

@freezed
class MyOrdersToPayListData with _$MyOrdersToPayListData {
  factory MyOrdersToPayListData({
    List<MyOrdersToPayData>? myOrdersData,
  }) = _MyOrdersToPayListData;

  factory MyOrdersToPayListData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersToPayListDataFromJson(json);
}

@freezed
class MyOrdersToPayData with _$MyOrdersToPayData {
  factory MyOrdersToPayData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "list_description") String? description,
    @JsonKey(name: "nested_data")
    List<MyOrdersToPayProductData>? myOrdersProdsData,
    @JsonKey(name: "amount_to_pay") double? amountToPay,
    @JsonKey(name: "t_qty") int? totalQty,
  }) = _MyOrdersToPayData;

  factory MyOrdersToPayData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersToPayDataFromJson(json);
}

@freezed
class MyOrdersToPayProductData with _$MyOrdersToPayProductData {
  factory MyOrdersToPayProductData({
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "key_name") String? keyName,
    @JsonKey(name: "value") String? knValue,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "quantity") int? qty,
  }) = _MyOrdersToPayProductData;

  factory MyOrdersToPayProductData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersToPayProductDataFromJson(json);
}

@freezed
class ProductDeliveryDetailsData with _$ProductDeliveryDetailsData {
  factory ProductDeliveryDetailsData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "primary_status") String? primaryStatus,
    @JsonKey(name: "description") String? description,
    @JsonKey(name: "recipients_name") String? recipientsName,
    @JsonKey(name: "unit_floor") String? unitFloor,
    @JsonKey(name: "st_bldg") String? stBldg,
    @JsonKey(name: "district") String? district,
    @JsonKey(name: "city") String? city,
    @JsonKey(name: "region") String? region,
    @JsonKey(name: "address_category") String? addressCategory,
    @JsonKey(name: "mobile_no") String? mobileNo,
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
  }) = _ProductDeliveryDetailsData;

  factory ProductDeliveryDetailsData.fromJson(Map<String, dynamic> json) =>
      _$ProductDeliveryDetailsDataFromJson(json);
}

@freezed
class ProductListDeliveryProgressDetailsData
    with _$ProductListDeliveryProgressDetailsData {
  factory ProductListDeliveryProgressDetailsData({
    List<ProductDeliveryProgressDetailsData>? delProgressList,
  }) = _ProductListDeliveryProgressDetailsData;

  factory ProductListDeliveryProgressDetailsData.fromJson(
          Map<String, dynamic> json) =>
      _$ProductListDeliveryProgressDetailsDataFromJson(json);
}

@freezed
class ProductDeliveryProgressDetailsData
    with _$ProductDeliveryProgressDetailsData {
  factory ProductDeliveryProgressDetailsData({
    @JsonKey(name: "com_usd_wrds") String? progressHeader,
    @JsonKey(name: "sub_progress")
    List<ProductSubDeliveryProgressDetailsData>? subProgress,
  }) = _ProductDeliveryProgressDetailsData;

  factory ProductDeliveryProgressDetailsData.fromJson(
          Map<String, dynamic> json) =>
      _$ProductDeliveryProgressDetailsDataFromJson(json);
}

@freezed
class ProductSubDeliveryProgressDetailsData
    with _$ProductSubDeliveryProgressDetailsData {
  factory ProductSubDeliveryProgressDetailsData({
    @JsonKey(name: "body_description") String? bodyDescription,
    @JsonKey(name: "dt_stamp") String? dtStamp,
  }) = _ProductSubDeliveryProgressDetailsData;

  factory ProductSubDeliveryProgressDetailsData.fromJson(
          Map<String, dynamic> json) =>
      _$ProductSubDeliveryProgressDetailsDataFromJson(json);
}

@freezed
class OrderDetailsData with _$OrderDetailsData {
  factory OrderDetailsData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "primary_status") String? primaryStatus,
    @JsonKey(name: "spc_description") String? description,
    @JsonKey(name: "nested_data")
    List<ProductOrderDetailsData>? myOrdersProdsData,
    @JsonKey(name: "amount_to_pay") double? amountToPay,
  }) = _OrderDetailsData;

  factory OrderDetailsData.fromJson(Map<String, dynamic> json) =>
      _$OrderDetailsDataFromJson(json);
}

@freezed
class ProductOrderDetailsData with _$ProductOrderDetailsData {
  factory ProductOrderDetailsData({
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "key_name") String? keyName,
    @JsonKey(name: "value") String? knValue,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "quantity") int? qty,
  }) = _ProductOrderDetailsData;

  factory ProductOrderDetailsData.fromJson(Map<String, dynamic> json) =>
      _$ProductOrderDetailsDataFromJson(json);
}

@freezed
class OrderDetailsSummaryData with _$OrderDetailsSummaryData {
  // I prefer to implement List<Map<String, dynamic>> instead of OrderDetailsSummaryData data model for better list generation of label and value
  factory OrderDetailsSummaryData({
    @JsonKey(name: "t_qty") int? totalQty,
    @JsonKey(name: "subtotal") double? subTotal,
    @JsonKey(name: "ship_f_subt") double? shippingFeeSubTotal,
    @JsonKey(name: "ship_f_disc_subt") double? shippingFeeDisc,
    @JsonKey(name: "vat") double? vat,
    @JsonKey(name: "coins") double? coins,
    @JsonKey(name: "glamgear_bal") double? glamGearBal,
    @JsonKey(name: "voucher") double? voucher,
    @JsonKey(name: "amount_to_pay") double? amountToPay,
  }) = _OrderDetailsSummaryData;

  factory OrderDetailsSummaryData.fromJson(Map<String, dynamic> json) =>
      _$OrderDetailsSummaryDataFromJson(json);
}

/// End of My Orders To Pay ///

/// Start of My Orders To Ship /// [TO ADD MORE GRANULAR CONTROL TO THE DATA MODEL]

@freezed
class MyOrdersToShipListData with _$MyOrdersToShipListData {
  factory MyOrdersToShipListData({
    List<MyOrdersToShipData>? myOrdersData,
  }) = _MyOrdersToShipListData;

  factory MyOrdersToShipListData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersToShipListDataFromJson(json);
}

@freezed
class MyOrdersToShipData with _$MyOrdersToShipData {
  factory MyOrdersToShipData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "com_usd_wrds") String? status,
    @JsonKey(name: "body_description") String? subStatus,
    @JsonKey(name: "list_description") String? description,
    @JsonKey(name: "nested_data")
    List<MyOrdersToShipProductData>? myOrdersProdsData,
    @JsonKey(name: "amount_to_pay") double? amountToPay,
    @JsonKey(name: "t_qty") int? totalQty,
  }) = _MyOrdersToShipData;

  factory MyOrdersToShipData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersToShipDataFromJson(json);
}

@freezed
class MyOrdersToShipProductData with _$MyOrdersToShipProductData {
  factory MyOrdersToShipProductData({
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "key_name") String? keyName,
    @JsonKey(name: "value") String? knValue,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "quantity") int? qty,
  }) = _MyOrdersToShipProductData;

  factory MyOrdersToShipProductData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersToShipProductDataFromJson(json);
}

/// End of My Orders To Ship ///

/// Start of My Orders To Receive /// [TO ADD MORE GRANULAR CONTROL TO THE DATA MODEL]

@freezed
class MyOrdersToReceiveListData with _$MyOrdersToReceiveListData {
  factory MyOrdersToReceiveListData({
    List<MyOrdersToReceiveData>? myOrdersData,
  }) = _MyOrdersToReceiveListData;

  factory MyOrdersToReceiveListData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersToReceiveListDataFromJson(json);
}

@freezed
class MyOrdersToReceiveData with _$MyOrdersToReceiveData {
  factory MyOrdersToReceiveData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "com_usd_wrds") String? status,
    @JsonKey(name: "list_description") String? description,
    @JsonKey(name: "nested_data")
    List<MyOrdersToReceiveProductData>? myOrdersProdsData,
    @JsonKey(name: "amount_to_pay") double? amountToPay,
    @JsonKey(name: "t_qty") int? totalQty,
  }) = _MyOrdersToReceiveData;

  factory MyOrdersToReceiveData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersToReceiveDataFromJson(json);
}

@freezed
class MyOrdersToReceiveProductData with _$MyOrdersToReceiveProductData {
  factory MyOrdersToReceiveProductData({
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "key_name") String? keyName,
    @JsonKey(name: "value") String? knValue,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "quantity") int? qty,
  }) = _MyOrdersToReceiveProductData;

  factory MyOrdersToReceiveProductData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersToReceiveProductDataFromJson(json);
}

/// End of My Orders To Receive ///

/// Start of My Orders All Purchased /// [TO ADD MORE GRANULAR CONTROL TO THE DATA MODEL]

@freezed
class MyOrdersAllPurchasedListData with _$MyOrdersAllPurchasedListData {
  factory MyOrdersAllPurchasedListData({
    List<MyOrdersAllPurchasedData>? myOrdersData,
  }) = _MyOrdersAllPurchasedListData;

  factory MyOrdersAllPurchasedListData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersAllPurchasedListDataFromJson(json);
}

@freezed
class MyOrdersAllPurchasedData with _$MyOrdersAllPurchasedData {
  factory MyOrdersAllPurchasedData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "com_usd_wrds") String? status,
    @JsonKey(name: "list_description") String? description,
    @JsonKey(name: "nested_data")
    List<MyOrdersAllPurchasedProductData>? myOrdersProdsData,
    @JsonKey(name: "amount_to_pay") double? amountToPay,
    @JsonKey(name: "t_qty") int? totalQty,
  }) = _MyOrdersAllPurchasedData;

  factory MyOrdersAllPurchasedData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersAllPurchasedDataFromJson(json);
}

@freezed
class MyOrdersAllPurchasedProductData with _$MyOrdersAllPurchasedProductData {
  factory MyOrdersAllPurchasedProductData({
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "key_name") String? keyName,
    @JsonKey(name: "value") String? knValue,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "quantity") int? qty,
  }) = _MyOrdersAllPurchasedProductData;

  factory MyOrdersAllPurchasedProductData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersAllPurchasedProductDataFromJson(json);
}

/// End of My Orders All Purchased ///

/// Start of My Orders Return / Refund /// [TO ADD MORE GRANULAR CONTROL TO THE DATA MODEL]

@freezed
class MyOrdersReturnRefListData with _$MyOrdersReturnRefListData {
  factory MyOrdersReturnRefListData({
    List<MyOrdersReturnRefData>? myOrdersData,
  }) = _MyOrdersReturnRefListData;

  factory MyOrdersReturnRefListData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersReturnRefListDataFromJson(json);
}

@freezed
class MyOrdersReturnRefData with _$MyOrdersReturnRefData {
  factory MyOrdersReturnRefData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "shipping_status") String? shippingStatus,
    @JsonKey(name: "nested_data")
    List<MyOrdersReturnRefProductData>? myOrdersProdsData,
    @JsonKey(name: "amount_to_pay") double? amountToPay,
    @JsonKey(name: "t_qty") int? totalQty,
  }) = _MyOrdersReturnRefData;

  factory MyOrdersReturnRefData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersReturnRefDataFromJson(json);
}

@freezed
class MyOrdersReturnRefProductData with _$MyOrdersReturnRefProductData {
  factory MyOrdersReturnRefProductData({
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "key_name") String? keyName,
    @JsonKey(name: "value") String? knValue,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "quantity") int? qty,
  }) = _MyOrdersReturnRefProductData;

  factory MyOrdersReturnRefProductData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersReturnRefProductDataFromJson(json);
}

/// End of My Orders Return / Refund ///

/// Start of My Orders Cancellation /// [TO ADD MORE GRANULAR CONTROL TO THE DATA MODEL]

@freezed
class MyOrdersCancellationListData with _$MyOrdersCancellationListData {
  factory MyOrdersCancellationListData({
    List<MyOrdersCancellationData>? myOrdersData,
  }) = _MyOrdersCancellationListData;

  factory MyOrdersCancellationListData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersCancellationListDataFromJson(json);
}

@freezed
class MyOrdersCancellationData with _$MyOrdersCancellationData {
  factory MyOrdersCancellationData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "list_description") String? description,
    @JsonKey(name: "nested_data")
    List<MyOrdersCancellationProductData>? myOrdersProdsData,
    @JsonKey(name: "amount_to_pay") double? amountToPay,
    @JsonKey(name: "t_qty") int? totalQty,
  }) = _MyOrdersCancellationData;

  factory MyOrdersCancellationData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersCancellationDataFromJson(json);
}

@freezed
class MyOrdersCancellationProductData with _$MyOrdersCancellationProductData {
  factory MyOrdersCancellationProductData({
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "key_name") String? keyName,
    @JsonKey(name: "value") String? knValue,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "quantity") int? qty,
  }) = _MyOrdersCancellationProductData;

  factory MyOrdersCancellationProductData.fromJson(Map<String, dynamic> json) =>
      _$MyOrdersCancellationProductDataFromJson(json);
}

@freezed
class CancelDetailsData with _$CancelDetailsData {
  factory CancelDetailsData({
    @JsonKey(name: "batch_id") String? batchID,
    @JsonKey(name: "primary_status") String? primaryStatus,
    @JsonKey(name: "spc_description") String? description,
    @JsonKey(name: "note_description") String? noteDescription,
    @JsonKey(name: "nested_data")
    List<CancelDetailsProductData>? myOrdersProdsData,
    @JsonKey(name: "is_refundable") bool? isRefundable,
    @JsonKey(name: "refundable") double? refundableAmt,
    @JsonKey(name: "current_step") int? currentStep,
    @JsonKey(name: "cancellation_d") String? cancellationDate,
  }) = _CancelDetailsData;

  factory CancelDetailsData.fromJson(Map<String, dynamic> json) =>
      _$CancelDetailsDataFromJson(json);
}

@freezed
class CancelDetailsProductData with _$CancelDetailsProductData {
  factory CancelDetailsProductData({
    @JsonKey(name: "img_data", fromJson: _fromBase64, toJson: _toBase64)
    Uint8List? imgData,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "key_name") String? keyName,
    @JsonKey(name: "value") String? knValue,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "quantity") int? qty,
  }) = _CancelDetailsProductData;

  factory CancelDetailsProductData.fromJson(Map<String, dynamic> json) =>
      _$CancelDetailsProductDataFromJson(json);
}

/// End of My Orders Cancellation ///

@freezed
class SubjectForEditAddressData with _$SubjectForEditAddressData {
  factory SubjectForEditAddressData({
    @JsonKey(name: "shipping_add_id") String? shipAddID,
    @JsonKey(name: "recipients_name") String? recipientName,
    @JsonKey(name: "mobile_no") String? mobileNo,
    @JsonKey(name: "region_index") int? regionIndex,
    @JsonKey(name: "region_code") String? regionCode,
    @JsonKey(name: "region_name") String? regionName,
    @JsonKey(name: "city_index") int? cityIndex,
    @JsonKey(name: "city_code") String? cityCode,
    @JsonKey(name: "city_name") String? cityName,
    @JsonKey(name: "district_index") int? districtIndex,
    @JsonKey(name: "district_code") String? districtCode,
    @JsonKey(name: "district_name") String? districtName,
    @JsonKey(name: "st_bldg") String? stBldg,
    @JsonKey(name: "unit_floor") String? unitFloor,
    @JsonKey(name: "address_category") String? addressCategory,
    @JsonKey(name: "is_default") bool? isDefault,
  }) = _SubjectForEditAddressData;

  factory SubjectForEditAddressData.fromJson(Map<String, dynamic> json) =>
      _$SubjectForEditAddressDataFromJson(json);
}
