import 'dart:convert';
import 'dart:typed_data';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:glamgear/internal/data_model/freezed/image_data.dart';
import 'package:glamgear/internal/data_model/freezed/prdct_admin_data.dart';

// required: associates our `prdct_client_data.dart` with the code generated by Freezed
// part 'prdct_client_data.freezed.dart'; // If prefer to use code generation using: dart run build_runner build
// optional: Since our ProductClientDashboardData class is serializable, we must add this line.
// But if ProductClientDashboardData was not serializable, we could skip it.
// part 'prdct_client_data.g.dart'; // If prefer to use code generation using: dart run build_runner build

/* To create the data model or to apply changes in the data model or there's modification in the method for @JsonKey(),
execute this command in terminal: dart run build_runner build --delete-conflicting-outputs*/

List<ProductPromoTag> _prodPromoTagFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ProductPromoTag.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _prodPromoTagToJson(List<ProductPromoTag>? prodPromoTagList) {
  return prodPromoTagList?.map((data) => data.toJson()).toList() ?? [];
}

List<ImageData> _imageDataFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ImageData.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _imageDataToJson(List<ImageData>? imageDataList) {
  return imageDataList?.map((data) => data.toJson()).toList() ?? [];
}

List<ImageDatawSub> _imageDatawSubFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ImageDatawSub.fromJson(json as Map<String, dynamic>))
      .toList();
} // needed to add another method

List<dynamic> _imageDatawSubToJson(List<ImageDatawSub>? imageDataList) {
  return imageDataList?.map((data) => data.toJson()).toList() ?? [];
}

List<ImageProdVarData> _imageProdVarDataFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ImageProdVarData.fromJson(json as Map<String, dynamic>))
      .toList();
} // needed to add another method

List<dynamic> _imageProdVarDataToJson(List<ImageProdVarData>? imageDataList) {
  return imageDataList?.map((data) => data.toJson()).toList() ?? [];
}

// String _prodDescFromJson(List<dynamic>? rawJson) {
//   return jsonEncode(rawJson ?? []);
// }

List<dynamic> _prodDescToJson(String? rawJson) {
  return jsonDecode(rawJson ?? '[]');
}

// Convert Base64 to Uint8List
Uint8List? _fromBase64(String? base64String) {
  if (base64String == null) return null;
  return base64Decode(base64String);
}

// Convert Uint8List to Base64 String
String? _toBase64(Uint8List? bytes) {
  if (bytes == null) return null;
  return base64Encode(bytes);
}