
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:glamgear/internal/data_model/freezed/image_data.dart';

// required: associates our `prdct_admin_data.dart` with the code generated by Freezed
part 'prdct_admin_data.freezed.dart';
// optional: Since our ProductAdminData class is serializable, we must add this line.
// But if ProductAdminData was not serializable, we could skip it.
part 'prdct_admin_data.g.dart';

/* To create the data model or to apply changes in the data model or there's modification in the method for @JsonKey(),
execute this command in terminal: dart run build_runner build --delete-conflicting-outputs*/

// Custom fromJson function
// List<PlatformFile>? _filesFromJson(List<dynamic> json) {
//   return json.map((fileJson) {
//     Map<String, dynamic> map = jsonDecode(fileJson);
//     return PlatformFile(
//       name: map['name'],
//       size: map['size'],
//       bytes: map['bytes'] != null ? base64Decode(map['bytes']) : null,
//     );
//   }).toList();
// }

// // Custom toJson function
// List<String> _filesToJson(List<PlatformFile>? files) {
//   return files!.map((file) {
//     return jsonEncode({
//       'name': file.name,
//       'size': file.size,
//       'bytes': file.bytes != null ? base64Encode(file.bytes!) : null,
//     });
//   }).toList();
// } // considered as an overhead at the moment

List<ProductData> _productDataFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ProductData.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _productDataToJson(List<ProductData>? productDataList) {
  return productDataList?.map((data) => data.toJson()).toList() ?? [];
}

List<ProductKeyValue> _prodKeyValFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ProductKeyValue.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _prodKeyValToJson(List<ProductKeyValue>? prodKeyValList) {
  return prodKeyValList?.map((data) => data.toJson()).toList() ?? [];
}

List<ImageData> _imageDataFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ImageData.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _imageDataToJson(List<ImageData>? imageDataList) {
  return imageDataList?.map((data) => data.toJson()).toList() ?? [];
}

List<ProductPromoTag> _prodPromoTagFromJson(List<dynamic>? jsonList) {
  return (jsonList ?? [])
      .map((json) => ProductPromoTag.fromJson(json as Map<String, dynamic>))
      .toList();
}

List<dynamic> _prodPromoTagToJson(List<ProductPromoTag>? prodPromoTagList) {
  return prodPromoTagList?.map((data) => data.toJson()).toList() ?? [];
}

@freezed
class ProductAdminData with _$ProductAdminData {
  factory ProductAdminData({
    @JsonKey(
        name: "json_data",
        fromJson: _productDataFromJson,
        toJson: _productDataToJson)
    List<ProductData>? productData,
  }) = _ProductAdminData;

  factory ProductAdminData.fromJson(Map<String, dynamic> json) =>
      _$ProductAdminDataFromJson(json);
}

@freezed
class ProductData with _$ProductData {
  factory ProductData({
    @JsonKey(name: "prod_id") String? prodId,
    @JsonKey(name: "prod_name") String? prodName,
    @JsonKey(name: "cat_name") String? category,
    @JsonKey(
        name: "nested_specs_key",
        fromJson: _prodKeyValFromJson,
        toJson: _prodKeyValToJson)
    List<ProductKeyValue>? prodKeyVal,
    @JsonKey(
        name: "nested_p_img_key",
        fromJson: _imageDataFromJson,
        toJson: _imageDataToJson)
    List<ImageData>? prodImg, // List of images with id
    @JsonKey(
        name: "nested_p_tag_key",
        fromJson: _prodPromoTagFromJson,
        toJson: _prodPromoTagToJson)
    List<ProductPromoTag>? prodPromoTag,
    @JsonKey(name: "orig_price") double? origPrice,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "value_added_tax") double? valueAddedTax,
    @JsonKey(name: "stock") int? stock,
    @JsonKey(name: "availability") bool? availability,
    @JsonKey(name: "desc_data") String? prodDescription,
    @JsonKey(name: "user_id_modifier") String? userIdModifier,
  }) = _ProductData;

  factory ProductData.fromJson(Map<String, dynamic> json) =>
      _$ProductDataFromJson(json);
}

@freezed
class ProductVarAdminData with _$ProductVarAdminData {
  factory ProductVarAdminData({
    @JsonKey(name: "pv_key_name_id") String? keyNameID,
    @JsonKey(name: "value") String? keyValue,
    @JsonKey(name: "orig_price") double? origPrice,
    @JsonKey(name: "disc_price") double? discPrice,
    @JsonKey(name: "value_added_tax") double? valueAddedTax,
    @JsonKey(name: "stock") int? stock,
    @JsonKey(name: "availability") bool? availability,
    List<ImageData>? prodImg, // List of images with sizes
    @JsonKey(name: "user_id_modifier") String? userIdModifier,
  }) = _ProductVarAdminData;

  factory ProductVarAdminData.fromJson(Map<String, dynamic> json) =>
      _$ProductVarAdminDataFromJson(json);
}

@freezed
class ProductKeyNames with _$ProductKeyNames {
  factory ProductKeyNames({
    List<ProductKeyName>? productKeyName,
    List<ProductVarKeyName>? productVarKeyName,
  }) = _ProductKeyNames;

  factory ProductKeyNames.fromJson(Map<String, dynamic> json) =>
      _$ProductKeyNamesFromJson(json);
}

@freezed
class ProductKeyName with _$ProductKeyName {
  factory ProductKeyName({
    @JsonKey(name: "p_key_name_id") String? prodKeyNameID,
    @JsonKey(name: "key_name") String? prodKeyName,
  }) = _ProductKeyName;

  factory ProductKeyName.fromJson(Map<String, dynamic> json) =>
      _$ProductKeyNameFromJson(json);
}

@freezed
class ProductVarKeyName with _$ProductVarKeyName {
  factory ProductVarKeyName({
    @JsonKey(name: "pv_key_name_id") String? prodVarKeyNameID,
    @JsonKey(name: "key_name") String? prodVarKeyName,
  }) = _ProductVarKeyName;

  factory ProductVarKeyName.fromJson(Map<String, dynamic> json) =>
      _$ProductVarKeyNameFromJson(json);
}

@freezed
class ProductKeyValue with _$ProductKeyValue {
  factory ProductKeyValue({
    @JsonKey(name: "p_key_name_id") String? prodKeyNameID,
    @JsonKey(name: "value") String? value,
  }) = _ProductKeyValue;

  factory ProductKeyValue.fromJson(Map<String, dynamic> json) =>
      _$ProductKeyValueFromJson(json);
}

@freezed
class ProductPromoTag with _$ProductPromoTag {
  factory ProductPromoTag({
    @JsonKey(name: "promo_tag_id") String? promoTagID,
    @JsonKey(name: "tag_values") String? tagValue,
  }) = _ProductPromoTag;

  factory ProductPromoTag.fromJson(Map<String, dynamic> json) =>
      _$ProductPromoTagFromJson(json);
}
