import 'dart:io';

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `user_data.dart` with the code generated by Freezed
part 'user_data.freezed.dart';
// optional: Since our UserData class is serializable, we must add this line.
// But if UserData was not serializable, we could skip it.
part 'user_data.g.dart';

File? _fileFromJson(String? path) {
  if (path == null) return null;
  return File(path);
}

String? _fileToJson(File? file) {
  return file?.path;
}

/* To create the data model or to apply changes in the data model or there's modification in the method for @JsonKey(),
execute this command in terminal: dart run build_runner build --delete-conflicting-outputs*/

@freezed
class UserData with _$UserData { // I prefer to not use this at the moment, but you can use it if you want to.
  factory UserData({
    String? userId,
    @JsonKey(fromJson: _fileFromJson, toJson: _fileToJson) File? frontIdImg,
    double? frontIdImgSize,
    @JsonKey(fromJson: _fileFromJson, toJson: _fileToJson) File? backIdImg,
    double? backIdImgSize,
    @JsonKey(fromJson: _fileFromJson, toJson: _fileToJson) File? selfieImg,
    double? selfieIdImgSize,
    String? givenName,
    String? middleName,
    String? familyName,
    String? suffix,
    String? gender,
    String? birthday,
    String? nationality,
    String? country,
    String? province,
    String? cityMun,
    String? brgy,
    String? unitHBldgSt,
    String? villSub,
    String? zipCode,
    String? sourceOfFund,
    String? empStatus,
    String? employer,
    String? occupation,
    String? mobileNo,
    String? password,
    String? functionKey,
  }) = _UserData;

  factory UserData.fromJson(Map<String, dynamic> json) =>
      _$UserDataFromJson(json);
}
